dependencies:
  /content/pages/about.md:
  - /content/pages/about.md
  - /content/pages/home.yaml
  - /content/pages/projects.md
  /content/pages/home.yaml:
  - /content/pages/about.md
  - /content/pages/home.yaml
  - /content/pages/projects.md
  /content/pages/projects.md:
  - /content/pages/about.md
  - /content/pages/home.yaml
  - /content/pages/projects.md
objects: {}
